import styles from "./page.module.css";
import { PictureSection, AuthorComponent } from "@/features/landing-page";
import { Footer } from "@/features/footer";

export default function Home() {
    return (
        <main className={styles.page}>
            <PictureSection
                title="Arte Para Todos"
                description="Generated by create next app. Generated by create next app. Generated by create next app"
                reverse={true}
                innerImage="/images/landing-page/book-cover.png"
            />
            <PictureSection
                title="Create Next App"
                description="Generated by create next app"
                image="/images/landing-page/color-background.jpg"
            />
            <AuthorComponent
                name="Madalith Pareja"
                description="Mada is an author and she wrote this book and it’s a good book. The best book, actually. There has never been a better book. People see this book and they say, wow, what a great book. I love this book. Joe has never written a book ike this."
                image="/images/landing-page/mada-pic.jpg"
            />
            <Footer />
        </main>
    );
}
